# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Trac
version:      1.000
version_from: lib/Template/Plugin/Trac.pm
installdirs:  site
requires:
    Template:                      0
    Test::More:                    0
    Text::Trac:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
